root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/debug"
  pre_cmd=["go mod tidy"]  
  cmd ="go build -gcflags='all=-N -l' -o ./tmp/debug /app/cmd/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin =  "dlv exec --headless=true --listen=:4000 --log=true --accept-multiclient --api-version=2 ./tmp/debug"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "500s"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true
  main_only = false
  level = "info"


[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true

[dev]
# Delve (dlv) will attach to this port
  open_browser = false
  auto_reload = true