version: '3.9'

services:
  project:
    build: .
    ports:  
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - postgres
    
  postgres:
    image: postgres:15.3-alpine3.18
    ports:
      - 5432:5432
    volumes:
      - ./initdb/database:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres