// Code generated by MockGen. DO NOT EDIT.
// Source: Project/pkg/app/user/port (interfaces: UserStorageInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_user_storage_interface.go -package=mocks Project/pkg/app/user/port UserStorageInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "Project/pkg/app/user/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserStorageInterface is a mock of UserStorageInterface interface.
type MockUserStorageInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserStorageInterfaceMockRecorder
}

// MockUserStorageInterfaceMockRecorder is the mock recorder for MockUserStorageInterface.
type MockUserStorageInterfaceMockRecorder struct {
	mock *MockUserStorageInterface
}

// NewMockUserStorageInterface creates a new mock instance.
func NewMockUserStorageInterface(ctrl *gomock.Controller) *MockUserStorageInterface {
	mock := &MockUserStorageInterface{ctrl: ctrl}
	mock.recorder = &MockUserStorageInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStorageInterface) EXPECT() *MockUserStorageInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserStorageInterface) Create(arg0 domain.CreateUserModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserStorageInterfaceMockRecorder) Create(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserStorageInterface)(nil).Create), arg0)
}

// GetUserByEmail mocks base method.
func (m *MockUserStorageInterface) GetUserByEmail(arg0 string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", arg0)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserStorageInterfaceMockRecorder) GetUserByEmail(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserStorageInterface)(nil).GetUserByEmail), arg0)
}

// UserUpdateName mocks base method.
func (m *MockUserStorageInterface) UserUpdateName(arg0 domain.UserUpdateName, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserUpdateName", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UserUpdateName indicates an expected call of UserUpdateName.
func (mr *MockUserStorageInterfaceMockRecorder) UserUpdateName(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserUpdateName", reflect.TypeOf((*MockUserStorageInterface)(nil).UserUpdateName), arg0, arg1)
}
